services:
  backend:
    build: .
    command: uvicorn app:app --host 0.0.0.0 --reload
    volumes:
      - ./app:/app
      - ./static:/static
    container_name: backend
    env_file: ".env"
    ports:
      - "8000:8000"
    depends_on:
      - postgresql
    networks:
      - my_network

  postgresql:
    image: postgres:latest
    ports:
      - "5432:5432"
    env_file: ".env"
    container_name: postgres
    volumes:
      - postgresql_volume:/var/lib/postgresql/data/
    networks:
      - my_network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/app.conf:/etc/nginx/conf.d/default.conf
      - ./static:/static
    container_name: nginx
    depends_on:
      - backend
    networks:
      - my_network

volumes:
  postgresql_volume:

networks:
  my_network:
    external: true